// Decompiled with Zomboid Decompiler v0.3.0 using Vineflower.
package zombie.scripting.objects;

public enum ItemDisplayCategory {
    ACCESSORY("Accessory"),
    AMMO("Ammo"),
    ANIMAL("Animal"),
    ANIMAL_PART("AnimalPart"),
    ANIMAL_PART_WEAPON("AnimalPartWeapon"),
    APPEARANCE("Appearance"),
    BADGER("Badger"),
    BAG("Bag"),
    BANDAGE("Bandage"),
    BEAR("Bear"),
    BEAVER("Beaver"),
    BROKEN_WEAPON("BrokenWeapon"),
    BUG("Bug"),
    BUNNY("Bunny"),
    CAMPING("Camping"),
    CARTOGRAPHY("Cartography"),
    CLOTHING("Clothing"),
    COMMUNICATIONS("Communications"),
    CONTAINER("Container"),
    COOKING("Cooking"),
    COOKING_WEAPON("CookingWeapon"),
    CORPSE("Corpse"),
    DOG("Dog"),
    DUCK("Duck"),
    EARS("Ears"),
    ELECTRONICS("Electronics"),
    ENTERTAINMENT("Entertainment"),
    EXPLOSIVES("Explosives"),
    EYE("Eye"),
    FIRE_SOURCE("FireSource"),
    FIRST_AID("FirstAid"),
    FIRST_AID_WEAPON("FirstAidWeapon"),
    FISHING("Fishing"),
    FISHING_WEAPON("FishingWeapon"),
    FOOD("Food"),
    FOX("Fox"),
    FROG("Frog"),
    FURNITURE("Furniture"),
    GARDENING("Gardening"),
    GARDENING_WEAPON("GardeningWeapon"),
    GENERIC("Generic"),
    GOBLIN("Goblin"),
    HEDGEHOG("Hedgehog"),
    HIDDEN("Hidden"),
    HOUSEHOLD("Household"),
    HOUSEHOLD_WEAPON("HouseholdWeapon"),
    INSTRUMENT("Instrument"),
    INSTRUMENT_WEAPON("InstrumentWeapon"),
    JUNK("Junk"),
    JUNK_WEAPON("JunkWeapon"),
    LIGHT_SOURCE("LightSource"),
    LITERATURE("Literature"),
    MALE_BODY("MaleBody"),
    MATERIAL("Material"),
    MATERIAL_WEAPON("MaterialWeapon"),
    MEMENTO("Memento"),
    MOLE("Mole"),
    PAINT("Paint"),
    PROTECTIVE_GEAR("ProtectiveGear"),
    RACCOON("Raccoon"),
    SECURITY("Security"),
    SKILL_BOOK("SkillBook"),
    SPIDER("Spider"),
    SPORTS("Sports"),
    SPORTS_WEAPON("SportsWeapon"),
    SQUIRREL("Squirrel"),
    TAIL("Tail"),
    TEDDY_BEAR("Teddy Bear"),
    TOOL("Tool"),
    TOOL_WEAPON("ToolWeapon"),
    TRAPPING("Trapping"),
    VEHICLE_MAINTENANCE("VehicleMaintenance"),
    VEHICLE_MAINTENANCE_WEAPON("VehicleMaintenanceWeapon"),
    WATER("Water"),
    WATER_CONTAINER("WaterContainer"),
    WEAPON("Weapon"),
    WEAPON_CRAFTED("WeaponCrafted"),
    WEAPON_IMPROVISED("WeaponImprovised"),
    WEAPON_PART("WeaponPart"),
    WOUND("Wound"),
    ZED_DMG("ZedDmg");

    private final String id;

    private ItemDisplayCategory(final String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return this.id;
    }
}
