// Decompiled with Zomboid Decompiler v0.3.0 using Vineflower.
package zombie.core;

import zombie.UsedFromLua;

@UsedFromLua
public enum CreditsName {
    ADAM_HANUS("Adam Hanus"),
    AFEKAY("Afekay"),
    AITOR_CRUZ("Aitor Garc\u00eda de la Cruz", "Garc\u00eda"),
    ALEKSANDRA_MIHAILOVA("Aleksandra \"Sasha\" Mihailova"),
    AMY_YOUNG("Amy \"Amz\" Young"),
    ANDRES_CASTRO("Andres \"Werlias\" Elias Gonzalez Castro", "Elias"),
    ANDY_HODGETTS("Andy \"Captain Binky\" Hodgetts"),
    AVI_GREENBURY("Avi Greenbury"),
    AYRTON_ORIO("Ayrton Orio"),
    BLAIR_FITZPATRICK("Blair Fitzpatrick"),
    CARL_STONE("Carl Stone"),
    CASEY_JO_KENNY("Casey-Jo Kenny"),
    CASPIAN_PRINCE("Caspian Prince"),
    CHRIS_SIMPSON("Chris \"Lemmy\" Simpson"),
    CHRIS_WOOD("Chris Wood"),
    CHRISTIAN_ALLEN("Christian \"Serellan\" Allen"),
    CLIFF_ANDERSON("Cliff Anderson"),
    CONNALL_LINDSAY("Connall \"Connall\" Lindsay"),
    DADDYDIRKIEDIRK("DaddyDirkieDirk"),
    DANIEL_HEELAN("Daniel \"MadDan\" Heelan"),
    DEREK_BUCHANAN("Derek Buchanan"),
    DYLAN_MYERS("Dylan Myers"),
    ELIA_TASSELL("Elia \"Misake\" Tassell"),
    EMMA_SMITH("Emma Smith"),
    ERIK_BROES("Erik \"Grum\" Broes"),
    ERIKA_EDGREN("Erika Edgren"),
    ERIS_CLARK("Eris Clark"),
    ERJAN_READ("E \"Frogski\" Read"),
    FILIBUSTER_RHYMES("Filibuster Rhymes"),
    FOX_CHAOTICA("Fox Chaotica"),
    ILJA_GAIDENKO("Ilja Gaidenko"),
    ISAAC_SALES("Isaac \"Calvy\" Sales"),
    JAMES_STRETTON("James \"Mr Sunshine\" Stretton"),
    JAMIE_MAGNUSON("Jamie \"Xeonyx\" Magnuson"),
    JAY_MILLS("Jay Mills"),
    JESSE_BURLAND_LOKKO("Jesse Burland-Lokko"),
    JOHNATHON_TINSLEY("Johnathon \"Kirrus\" Tinsley"),
    KEES_BEKKEMA("Kees \"Turbo\" Bekkema"),
    KEVIN_BANKS("Kevin \"Vaileasys\" Banks"),
    MARINA_SIU_CHONG("Marina \"Mash\" Siu-Chong"),
    MARK_ROWLEY("Mark Rowley"),
    MARK_WRIGHT("Mark Wright"),
    MARTIN_GREENALL("Martin Greenall"),
    MARTIN_NEHRDICH("Martin \"nasKo\" Nehrdich"),
    MASON_PARADA("Mason Parada"),
    MATTHEW_HARBER("Matthew \"theharber\" Harber"),
    MATTHEW_SULLIVAN("Matt \"AmazingSully\" Sullivan"),
    MAX_BRODE("Max Brode"),
    MAX_NUTTALL("Max \"Kelpie\" Nuttall"),
    MICHAL_CHECINSKI("Micha\u0142 \"Faalagorn\" Ch\u0119ci\u0144ski"),
    MIKE_BERRY("Mike \"mb\" Berry"),
    NICK_COWEN("Nick Cowen"),
    NIKOLA_KAPIDZIC("Nikola Kapid\u017ei\u0107"),
    NORMAN_VEZINA("Norman \"Baph\" Vezina"),
    PATRICK_BRENNAN("Patrick Brennan"),
    PATRICK_BROTT("Patrick Brott"),
    PAUL_RING("Paul \"RingoD\" Ring"),
    RAPHAEL_BARANDAS("Raphael \"Soul Filcher\" Motizuki Barandas", "Motizuki"),
    RICHARD_CABAN("Richard \"Beard\" Caban"),
    ROMAIN_DRON("Romain \"RJ\" Dron"),
    SAM_SPAWTON("Sam Spawton"),
    SPIFFO("Spiffo"),
    STEPHEN_REID("Stephen Reid"),
    STEVE_NORTH("Steve North"),
    STEVE_SHARP("Steve Sharp"),
    STUART_JONES("Stuart Jones"),
    THOMAS_GUIMBRETIERE("Thomas \"ProfMobius\" Guimbretiere"),
    TIMOTHY_BAKER("Timothy Baker"),
    UNCONID("Unconid"),
    WILL_PORTER("Will Porter"),
    YANA_DUNCAN("Yana Marszalkowska - Duncan"),
    ZAC_CONGO("Zac Congo"),
    ZACH_BEEVER("Zach Beever"),
    ALEKSEI_KHOKHOLOV("Aleksei Khokholov"),
    ALEXANDER_BLINOV("Alexander Blinov"),
    ANDREI_MELNIKOV("Andrei Melnikov"),
    ANDREI_TOPILIN("Andrei Topilin"),
    ARMIN_HAAS("Armin Haas"),
    ARTEM_BORDYUGOV("Artem Bordyugov"),
    ASH_BLAKE_HOOD("Ash Blake-Hood"),
    BAURZHAN_SITKALIEV("Baurzhan Sitkaliev"),
    BYRON_BULLOCK("Byron Bullock"),
    CHRISTOPHER_SCHNITZERLING("Christopher Schnitzerling"),
    DANIIL_KLESHCHEVNIKOV("Daniil Kleshchevnikov"),
    DAVID_PHILIPP("David Philipp"),
    FLAVIA_TACONI("Flavia Taconi"),
    GENNADII_POTAPOV("Gennadii Potapov"),
    ILIA_TEPLISHCHEV("Ilia Teplishchev"),
    INNOKENTIY_SEDOV("Innokentiy Sedov"),
    IURI_IAKOVLEV("Iurii Iakovlev"),
    JACK_BELL("Jack Bell"),
    JEMMA_RILEY_TOLCH("Jemma Riley-Tolch"),
    JONATHAN_BURSAC("Jonathan Bursac"),
    KASIA_DZIEKAN("Kasia Dziekan"),
    KYLE_ROWLEY("Kyle Rowley"),
    LORENZO_PIANI("Lorenzo Piani"),
    MATTEO_LUPIERI("Matteo Lupieri"),
    MATTHIAS_WOLF("Matthias Wolf"),
    MICHAEL_HARTUNG("Michael Hartung"),
    MIKHAIL_GUDIM("Mikhail Gudim"),
    NATALIA_ROWLEY("Natalia Rowley"),
    NICHOLAS_STEVENS("Nicholas Stevens"),
    SCOTT_PURCIVAL("Scott Purcival"),
    SERGEI_SHUBIN("Sergei Shubin"),
    THOMAS_DEYN("Thomas De Deyn", "De"),
    YANNICK_WINTER("Yannick Winter"),
    A_BRICK_FAIRY("a_brick_fairy"),
    ADRIC_HARTIN("Adric \"AdricTheGreat\" Hartin"),
    ALAIN_DELLEPIANE("Alain Dellepiane"),
    ALAN_CARTER("Alan Carter"),
    ALBION("albion"),
    ALEXA_ALTEZ("Alexa \"PepperCat\" Altez"),
    ALICE_BONNEAU("Alice \"ALL14\" Bonneau"),
    AMBIGUOUSAMPHIBIAN("ambiguousamphibian"),
    ANDRÁS_ÁCS("Andr\u00e1s \u00c1cs"),
    ANGELA_BATEMAN("Angela Bateman"),
    ANNA_SHEVCHENKO("Anna Shevchenko"),
    ANONYMOUS("Anonymous"),
    ANTTI_RIIKONEN("Antti \"harakka\" Riikonen"),
    ASIA_MLECZAK("Asia Mleczak"),
    AWPENHEIMER("Awpenheimer"),
    BARBARA_MONTI("Barbara Monti"),
    BEAR_GRANANDER("Bear \"Markofbear\" Granander"),
    BENJAMIN_JAMES("Benjamin \"Bejasc\" James"),
    BENJAMIN_SCHIEDER("Benjamin \"blindcoder\" Schieder"),
    BILL_REDPATH("Bill \"wait what?\" Redpath"),
    BOBHECKLING("BobHeckling"),
    BOXER("Boxer"),
    BRIAN_HICKS("Brian Hicks"),
    CALLY("Cally"),
    CHARLIE_SLOAN("Charlie \"ToastedFishSandwich\" Sloan"),
    CHET_FALISZEK("Chet Faliszek"),
    CHIEF("Chief"),
    CHRISTIAN_JORGE("Christian \"Snake\" Jorge"),
    CHRISTIAN_WALBER("Christian \"Thuztor\" Walber"),
    CHRISTOPHER_GREEN("Christopher \"Augur\" Green"),
    CILLIAN_JUNG("Cillian Jung"),
    CLEMENT_GIRAUDEAU("Cl\u00e9ment \"deprav\" Giraudeau"),
    CROMULENT_ARCHER("Cromulent Archer"),
    DANIEL_MARQUES("Daniel Marques"),
    DANIEL_SOBHI("Daniel \"Clerkius\" Sobhi"),
    DEAN_HALL("Dean \"Rocket\" Hall"),
    DEAN_TROTMAN("Dean Trotman"),
    DEMI_BARTELS("Demi Bartels"),
    DITOSEADIO("ditoseadio"),
    DMITRY_BOROVSKY("Dmitry \"Oneline\" Borovsky"),
    DR_COX1911("Dr_Cox1911"),
    DRAKE_BARRON("Drake \"Rathlord\" Barron"),
    DUFFY_DAVIS("Duffy Davis"),
    ECKYMAN("Eckyman"),
    EDWARD_SMALLWOOD("Edward \"Zargo\" Smallwood"),
    EDWIN_TRAN("Edwin \"mid\" Tran"),
    ELSPETH_EDMONDS("Elspeth Edmonds"),
    EMILY_RICHARDSON("Emily Richardson"),
    FRANCOIS_DESFORGES("Fran\u00e7ois \"FlashFire\" Desforges"),
    FRANK_JORDAN("Frank 'Kellykellz' Jordan"),
    GRAEME_STRUTHERS("Graeme Struthers"),
    HELEEN_WIEMANS("Heleen Wiemans"),
    HENRY_PATTERSON("Henry Patterson"),
    HENRY_SHU("Henry Shu"),
    HESTER_LEISTRA("Hester Leistra"),
    HOODIE_GUY("Hoodie Guy"),
    HYESU_CHOE("Hyesu Choe"),
    IRIS_KUPPEN("Iris Kuppen"),
    JACOB_HALEY("Jacob \"Freeplayo7\" Haley"),
    JAIME_BYRNE("Jaime Byrne"),
    JAKOB_KANDEL("Jakob Kandel"),
    JAS_PUREWAL("Jas Purewal"),
    JONES_GAMBARINE("Jones \"Gambarine\""),
    JORGE_GUEDES("Jorge Guedes"),
    JOSH_HENNING("Josh Henning"),
    JUNWON_KONG("Junwon Kong"),
    KAROLINA_BARSZCZ("Karolina Barszcz"),
    KEVIN_KING("Kevin \"KPK\" P. King"),
    KIERAN_RAFFERTY("Kieran \"Stormy\" Rafferty"),
    KIM_METZGER("Kim \"ZonaryQuasar\" Metzger"),
    KIWO("Kiwo"),
    KLEAN("Klean"),
    KONSTANTIN_KOPIN("Konstantin Kopin"),
    KRISTINE_MYRENE("Kristine Myrene"),
    KRZYSZTOF_SAGOLA("Krzysztof \"geras\" Sagola"),
    LEO_DIMILO("Leo \"Drunkonlife\" Dimilo"),
    LEO_IVANOV("Leo Ivanov"),
    LEONKIEL("LeonKiel"),
    LINDA_MYRWOLD("Linda Myrwold"),
    LIWEN_ZHANG("Liwen Zhang"),
    LORENZO_BERTOLUCCI("Lorenzo Bertolucci"),
    LOUIS_KEEP("Louis \"Keepbro\" Keep"),
    MACA("Maca Fern\u00e1ndez"),
    MARC_TOOKEY("Marc \"The Pleasure\" Tookey"),
    MARCO_PURSCHLER("Marco \"TwisTonFire\" P\u00fcrschler"),
    MARCUS_GONCALVES("Marcus \"Mark_MartinsBR\" Gon\u00e7alves"),
    MARCUS_HILL("Marcus \"dThunder\" Hill"),
    MARK_EXE("Mark.exe"),
    MARK_SANDERS("Mark \"EreWeGo\" Sanders"),
    MATHAS("Mathas"),
    MATHILDACHAN("mathildachan"),
    MATT_RITCHIE("Matt Ritchie"),
    MATT_SCHILLACI("Matt Schillaci"),
    MATTEO_SCARABELLI("Matteo Scarabelli"),
    MAYATUTORS("MayaTutors"),
    MICHAEL_HAZELWOOD("Michael \"ThinkDock1721\" Hazelwood"),
    MIDDLEAGEDBOB("MiddleAgedBob"),
    MILLER_MEI("Miller Mei"),
    MISTER_LAMPREY("Mister Lamprey"),
    MR_BROLLOW("Mr. Brollow"),
    MR_L_TARTAN("Mr Du Bois (L.Tartan)"),
    MRATOMICDUCK("MrAtomicDuck"),
    NATALIA_PATEREK("Natalia Paterek"),
    NJ_APOSTOL("NJ Apostol"),
    NOTCH("Notch"),
    OLIVIA_WHITE("Olivia White"),
    ORSOLYA_LIPTAY("Orsolya Liptay"),
    PAUL_JR("Paul Soares Jr"),
    PAUL_MCALOON("Paul \"Dr Gonzo\" McAloon"),
    PAUL_WRIGHT("Paul \"mendonca\" Wright"),
    PETER_LEE("Peter Lee"),
    PETER_LEWIN("Peter Lewin"),
    PETER_LOVERSO("Peter \"rdsqc22\" LoVerso"),
    PHILL_CAMERON("Phill Cameron"),
    PIOTR_HELAK("Piotr Helak"),
    PR1VATELIME("Pr1vateLime"),
    PUPPERS("Puppers"),
    RASMUS_NIELSEN("Rasmus \"LennyLeak\" Nielsen"),
    REDWIRE("Redwire"),
    REKKIE("Rekkie"),
    ROBBAZ("Robbaz"),
    ROBOMAT("RoboMat"),
    ROMUALD_DRON("Romuald Dron"),
    ROYALEWITHCHEESE("RoyaleWithCheese"),
    RUAL_STORGE("Rual Storge"),
    SACRIEL("Sacriel"),
    SAMI_OLAVI("Sami Olavi"),
    SARAH_NEWELL("Sarah Newell"),
    SAUDIGAMER("SaudiGamer"),
    SAVELIY_ZELOVSKIY("Saveliy Zelovskiy"),
    SCOTT_REISMANIS("Scott Reismanis"),
    SHANNON_KILLER("Shannon Z Killer"),
    SHARPGOLDEN("sharpgolden"),
    SIMON_CADET("Simon \"SimKDT\" Cadet"),
    STEVE_YOUNG("Steve \"syefye\" Young"),
    TANJA_SUITIALA("Tanja Suitiala"),
    THE_COMMANDER("The Commander"),
    THE_COMMUNITY("The PZ Community"),
    THE_PUB("The guy outside the pub"),
    THOR_PENTHIN_GRUMLØSE("Thor Penthin Gruml\u00f8se"),
    TIM_BUCKLEY("Tim Buckley"),
    TITOPEI("titopei"),
    TOM_PORTER("Tom Porter"),
    TOMEK_KALISZEWSKI("Tomek Kaliszewski"),
    TRAILER_FARM("Trailer Farm"),
    TWIGGY("Twiggy"),
    TZU_SHENG_HSIAO("Tzu-Sheng Hsiao"),
    VIBRANCE("Vibrance"),
    VICKI_WOODS("Vicki Ann Woods"),
    WOJCIECH_BRUDZIŃSKI("Wojciech Brudzi\u0144ski"),
    YICHING_CHOU("Yiching Chou"),
    YULIIA_TATSENKO("Yuliia Tatsenko");

    private final String name;
    private final String sort;

    private CreditsName(final String name) {
        String[] nameSplit = name.split(" ");
        this(name, nameSplit[nameSplit.length - 1]);
    }

    private CreditsName(final String name, final String sort) {
        this.name = name;
        this.sort = sort.toUpperCase();
    }

    public String getName() {
        return this.name;
    }

    public String getSort() {
        return this.sort;
    }
}
