// Decompiled with Zomboid Decompiler v0.3.0 using Vineflower.
package zombie.core.properties;

import zombie.UsedFromLua;
import zombie.scripting.objects.Registries;
import zombie.scripting.objects.RegistryReset;
import zombie.scripting.objects.ResourceLocation;

@UsedFromLua
public final class TilePropertyKey {
    public static final TilePropertyKey ALWAYS_DRAW = registerBase("alwaysDraw");
    public static final TilePropertyKey AMBIENT_SOUND = registerBase("AmbientSound");
    public static final TilePropertyKey ATTACHED_CEILING = registerBase("attachedCeiling");
    public static final TilePropertyKey ATTACHED_E = registerBase("attachedE");
    public static final TilePropertyKey ATTACHED_FLOOR = registerBase("AttachedFloor");
    public static final TilePropertyKey ATTACHED_N = registerBase("attachedN");
    public static final TilePropertyKey ATTACHED_NW = registerBase("attachedNW");
    public static final TilePropertyKey ATTACHED_S = registerBase("attachedS");
    public static final TilePropertyKey ATTACHED_SE = registerBase("attachedSE");
    public static final TilePropertyKey ATTACHED_SURFACE = registerBase("attachedSurface");
    public static final TilePropertyKey ATTACHED_TO_GLASS = registerBase("AttachedToGlass");
    public static final TilePropertyKey ATTACHED_W = registerBase("attachedW");
    public static final TilePropertyKey ATTACH_TO_STAIRS = registerBase("attachtostairs");
    public static final TilePropertyKey BED = registerBase("bed");
    public static final TilePropertyKey BED_TYPE = registerBase("BedType");
    public static final TilePropertyKey BLOCKS_PLACEMENT = registerBase("BlocksPlacement");
    public static final TilePropertyKey BLOCK_RAIN = registerBase("BlockRain");
    public static final TilePropertyKey BLOCK_SIGHT = registerBase("blocksight");
    public static final TilePropertyKey BLUEPRINT = registerBase("blueprint");
    public static final TilePropertyKey BURNING = registerBase("burning");
    public static final TilePropertyKey BURNT_OUT = registerBase("burntOut");
    public static final TilePropertyKey BURNT_TILE = registerBase("BurntTile");
    public static final TilePropertyKey BUSH = registerBase("Bush");
    public static final TilePropertyKey CANT_CLIMB = registerBase("CantClimb");
    public static final TilePropertyKey CAN_ATTACH_ANIMAL = registerBase("CanAttachAnimal");
    public static final TilePropertyKey CAN_BE_CUT = registerBase("canBeCut");
    public static final TilePropertyKey CAN_BE_REMOVED = registerBase("canBeRemoved");
    public static final TilePropertyKey CAN_BREAK = registerBase("CanBreak");
    public static final TilePropertyKey CAN_PATH_N = registerBase("canPathN");
    public static final TilePropertyKey CAN_PATH_W = registerBase("canPathW");
    public static final TilePropertyKey CAN_SCRAP = registerBase("CanScrap");
    public static final TilePropertyKey CAR_SLOW_FACTOR = registerBase("CarSlowFactor");
    public static final TilePropertyKey CHAIR_E = registerBase("chairE");
    public static final TilePropertyKey CHAIR_N = registerBase("chairN");
    public static final TilePropertyKey CHAIR_S = registerBase("chairS");
    public static final TilePropertyKey CHAIR_W = registerBase("chairW");
    public static final TilePropertyKey CLIMB_SHEET_E = registerBase("climbSheetE");
    public static final TilePropertyKey CLIMB_SHEET_N = registerBase("climbSheetN");
    public static final TilePropertyKey CLIMB_SHEET_S = registerBase("climbSheetS");
    public static final TilePropertyKey CLIMB_SHEET_TOP_E = registerBase("climbSheetTopE");
    public static final TilePropertyKey CLIMB_SHEET_TOP_N = registerBase("climbSheetTopN");
    public static final TilePropertyKey CLIMB_SHEET_TOP_S = registerBase("climbSheetTopS");
    public static final TilePropertyKey CLIMB_SHEET_TOP_W = registerBase("climbSheetTopW");
    public static final TilePropertyKey CLIMB_SHEET_W = registerBase("climbSheetW");
    public static final TilePropertyKey CLOSE_SNEAK_BONUS = registerBase("CloseSneakBonus");
    public static final TilePropertyKey COLLIDE_N = registerBase("collideN");
    public static final TilePropertyKey COLLIDE_W = registerBase("collideW");
    public static final TilePropertyKey CONNECT_X = registerBase("connectX");
    public static final TilePropertyKey CONNECT_Y = registerBase("connectY");
    public static final TilePropertyKey CONTAINER = registerBase("container");
    public static final TilePropertyKey CONTAINER_CAPACITY = registerBase("ContainerCapacity");
    public static final TilePropertyKey CONTAINER_CLOSE_SOUND = registerBase("ContainerCloseSound");
    public static final TilePropertyKey CONTAINER_OPEN_SOUND = registerBase("ContainerOpenSound");
    public static final TilePropertyKey CONTAINER_POSITION = registerBase("ContainerPosition");
    public static final TilePropertyKey CONTAINER_PUT_SOUND = registerBase("ContainerPutSound");
    public static final TilePropertyKey CONTAINER_TAKE_SOUND = registerBase("ContainerTakeSound");
    public static final TilePropertyKey CORNER_NORTH_WALL = registerBase("CornerNorthWall");
    public static final TilePropertyKey CORNER_WEST_WALL = registerBase("CornerWestWall");
    public static final TilePropertyKey CURTAIN_E = registerBase("curtainE");
    public static final TilePropertyKey CURTAIN_N = registerBase("curtainN");
    public static final TilePropertyKey CURTAIN_OFFSET = registerBase("CurtainOffset");
    public static final TilePropertyKey CURTAIN_S = registerBase("curtainS");
    public static final TilePropertyKey CURTAIN_SOUND = registerBase("CurtainSound");
    public static final TilePropertyKey CURTAIN_W = registerBase("curtainW");
    public static final TilePropertyKey CUSTOM_ITEM = registerBase("CustomItem");
    public static final TilePropertyKey CUSTOM_NAME = registerBase("CustomName");
    public static final TilePropertyKey CUTAWAY_HINT = registerBase("CutawayHint");
    public static final TilePropertyKey CUT_N = registerBase("cutN");
    public static final TilePropertyKey CUT_W = registerBase("cutW");
    public static final TilePropertyKey DAMAGED_SPRITE = registerBase("DamagedSprite");
    public static final TilePropertyKey DIAMOND_FLOOR = registerBase("diamondFloor");
    public static final TilePropertyKey DOOR_FR_N = registerBase("doorFrN");
    public static final TilePropertyKey DOOR_FR_W = registerBase("doorFrW");
    public static final TilePropertyKey DOOR_N = registerBase("doorN");
    public static final TilePropertyKey DOOR_SOUND = registerBase("DoorSound");
    public static final TilePropertyKey DOOR_TRANS = registerBase("doorTrans");
    public static final TilePropertyKey DOOR_W = registerBase("doorW");
    public static final TilePropertyKey DOOR_WALL_N = registerBase("DoorWallN");
    public static final TilePropertyKey DOOR_WALL_NW = registerBase("DoorWallNW");
    public static final TilePropertyKey DOOR_WALL_NW_TRANS = registerBase("DoorWallNWTrans");
    public static final TilePropertyKey DOOR_WALL_N_TRANS = registerBase("DoorWallNTrans");
    public static final TilePropertyKey DOOR_WALL_W = registerBase("DoorWallW");
    public static final TilePropertyKey DOOR_WALL_W_TRANS = registerBase("DoorWallWTrans");
    public static final TilePropertyKey DOUBLE_DOOR = registerBase("DoubleDoor");
    public static final TilePropertyKey DOUBLE_DOOR_1 = registerBase("DoubleDoor1");
    public static final TilePropertyKey DOUBLE_DOOR_2 = registerBase("DoubleDoor2");
    public static final TilePropertyKey ENTITY_SCRIPT = registerBase("EntityScript");
    public static final TilePropertyKey ENTITY_SCRIPT_NAME = registerBase("EntityScriptName");
    public static final TilePropertyKey EXTERIOR = registerBase("exterior");
    public static final TilePropertyKey E_OFFSET = registerBase("Eoffset");
    public static final TilePropertyKey FACING = registerBase("Facing");
    public static final TilePropertyKey FASCIA_EDGE = registerBase("FasciaEdge");
    public static final TilePropertyKey FASCIA_EDGE_REVERSIBLE = registerBase("FasciaEdgeReversible");
    public static final TilePropertyKey FENCE_TYPE_HIGH = registerBase("FenceTypeHigh");
    public static final TilePropertyKey FENCE_TYPE_LOW = registerBase("FenceTypeLow");
    public static final TilePropertyKey FIRE_REQUIREMENT = registerBase("firerequirement");
    public static final TilePropertyKey FLOOR_ATTACHMENT_E = registerBase("FloorAttachmentE");
    public static final TilePropertyKey FLOOR_ATTACHMENT_N = registerBase("FloorAttachmentN");
    public static final TilePropertyKey FLOOR_ATTACHMENT_S = registerBase("FloorAttachmentS");
    public static final TilePropertyKey FLOOR_ATTACHMENT_W = registerBase("FloorAttachmentW");
    public static final TilePropertyKey FLOOR_HEIGHT = registerBase("FloorHeight");
    public static final TilePropertyKey FLOOR_HEIGHT_ONE_THIRD = registerBase("FloorHeightOneThird");
    public static final TilePropertyKey FLOOR_HEIGHT_TWO_THIRDS = registerBase("FloorHeightTwoThirds");
    public static final TilePropertyKey FLOOR_MATERIAL = registerBase("FloorMaterial");
    public static final TilePropertyKey FLOOR_OVERLAY = registerBase("FloorOverlay");
    public static final TilePropertyKey FOOTSTEP_MATERIAL = registerBase("FootstepMaterial");
    public static final TilePropertyKey FORCED_LOCKED = registerBase("forcedLocked");
    public static final TilePropertyKey FORCE_AMBIENT = registerBase("ForceAmbient");
    public static final TilePropertyKey FORCE_FADE = registerBase("forceFade");
    public static final TilePropertyKey FORCE_LOCKED = registerBase("forceLocked");
    public static final TilePropertyKey FORCE_RENDER = registerBase("forceRender");
    public static final TilePropertyKey FORCE_SINGLE_ITEM = registerBase("ForceSingleItem");
    public static final TilePropertyKey FREEZER = registerBase("Freezer");
    public static final TilePropertyKey FREEZER_CAPACITY = registerBase("FreezerCapacity");
    public static final TilePropertyKey FREEZER_POSITION = registerBase("FreezerPosition");
    public static final TilePropertyKey FUEL_AMOUNT = registerBase("fuelAmount");
    public static final TilePropertyKey GARAGE_DOOR = registerBase("GarageDoor");
    public static final TilePropertyKey GENERATOR_SOUND = registerBase("GeneratorSound");
    public static final TilePropertyKey GENERIC_CRAFTING_SURFACE = registerBase("GenericCraftingSurface");
    public static final TilePropertyKey GLASS_REMOVED_OFFSET = registerBase("GlassRemovedOffset");
    public static final TilePropertyKey GRASS_FLOOR = registerBase("grassFloor");
    public static final TilePropertyKey GRIME_TYPE = registerBase("GrimeType");
    public static final TilePropertyKey GROUP_NAME = registerBase("GroupName");
    public static final TilePropertyKey HALF_HEIGHT = registerBase("halfheight");
    public static final TilePropertyKey HAS_LIGHT_ON_SPRITE = registerBase("HasLightOnSprite");
    public static final TilePropertyKey HAS_RAINDROP = registerBase("HasRaindrop");
    public static final TilePropertyKey HAS_RAIN_SPLASHES = registerBase("HasRainSplashes");
    public static final TilePropertyKey HIDE_WALLS = registerBase("hidewalls");
    public static final TilePropertyKey HIT_BY_CAR = registerBase("HitByCar");
    public static final TilePropertyKey HOPPABLE_N = registerBase("HoppableN");
    public static final TilePropertyKey HOPPABLE_W = registerBase("HoppableW");
    public static final TilePropertyKey IGNORE_SURFACE_SNAP = registerBase("IgnoreSurfaceSnap");
    public static final TilePropertyKey INTERIOR = registerBase("interior");
    public static final TilePropertyKey INTERIOR_SIDE = registerBase("InteriorSide");
    public static final TilePropertyKey INVISIBLE = registerBase("invisible");
    public static final TilePropertyKey ISO_TYPE = registerBase("IsoType");
    public static final TilePropertyKey IS_CLOSED_STATE = registerBase("IsClosedState");
    public static final TilePropertyKey IS_EAVE = registerBase("isEave");
    public static final TilePropertyKey IS_FLOOR_ATTACHED = registerBase("IsFloorAttached");
    public static final TilePropertyKey IS_FRIDGE = registerBase("IsFridge");
    public static final TilePropertyKey IS_GRID_EXTENSION_TILE = registerBase("IsGridExtensionTile");
    public static final TilePropertyKey IS_HIGH = registerBase("IsHigh");
    public static final TilePropertyKey IS_LOW = registerBase("IsLow");
    public static final TilePropertyKey IS_MIRROR = registerBase("IsMirror");
    public static final TilePropertyKey IS_MOVE_ABLE = registerBase("IsMoveAble");
    public static final TilePropertyKey IS_MOVE_ABLE_OBJECT = registerBase("isMoveAbleObject");
    public static final TilePropertyKey IS_PAINTABLE = registerBase("IsPaintable");
    public static final TilePropertyKey IS_STACKABLE = registerBase("IsStackable");
    public static final TilePropertyKey IS_SURFACE_OFFSET = registerBase("IsSurfaceOffset");
    public static final TilePropertyKey IS_TABLE = registerBase("IsTable");
    public static final TilePropertyKey IS_TABLE_TOP = registerBase("IsTableTop");
    public static final TilePropertyKey IS_TRASH_CAN = registerBase("IsTrashCan");
    public static final TilePropertyKey IS_WATER_COLLECTOR = registerBase("IsWaterCollector");
    public static final TilePropertyKey ITEM_HEIGHT = registerBase("ItemHeight");
    public static final TilePropertyKey JUKEBOX = registerBase("jukebox");
    public static final TilePropertyKey LIGHTSWITCH = registerBase("lightswitch");
    public static final TilePropertyKey LIGHT_B = registerBase("lightB");
    public static final TilePropertyKey LIGHT_FILTER_B = registerBase("LightFilterB");
    public static final TilePropertyKey LIGHT_FILTER_G = registerBase("LightFilterG");
    public static final TilePropertyKey LIGHT_FILTER_INTENSITY = registerBase("LightFilterIntensity");
    public static final TilePropertyKey LIGHT_FILTER_MIX = registerBase("LightFilterMix");
    public static final TilePropertyKey LIGHT_FILTER_R = registerBase("LightFilterR");
    public static final TilePropertyKey LIGHT_G = registerBase("lightG");
    public static final TilePropertyKey LIGHT_R = registerBase("lightR");
    public static final TilePropertyKey LIGHT_RADIUS = registerBase("LightRadius");
    public static final TilePropertyKey LINKED_LOC_IS = registerBase("LinkedLocIs");
    public static final TilePropertyKey LINKED_OFFSET = registerBase("LinkedOffset");
    public static final TilePropertyKey LIVING_ROOM = registerBase("livingRoom");
    public static final TilePropertyKey MAKE_WINDOW_INVINCIBLE = registerBase("makeWindowInvincible");
    public static final TilePropertyKey MATERIAL = registerBase("Material");
    public static final TilePropertyKey MATERIAL_2 = registerBase("Material2");
    public static final TilePropertyKey MATERIAL_3 = registerBase("Material3");
    public static final TilePropertyKey MATERIAL_TYPE = registerBase("MaterialType");
    public static final TilePropertyKey MICROWAVE = registerBase("Microwave");
    public static final TilePropertyKey MINIMUM_CAR_SPEED_DMG = registerBase("MinimumCarSpeedDmg");
    public static final TilePropertyKey MOVEMENT = registerBase("Movement");
    public static final TilePropertyKey MOVE_TYPE = registerBase("MoveType");
    public static final TilePropertyKey MOVE_WITH_WIND = registerBase("MoveWithWind");
    public static final TilePropertyKey NAME = registerBase("name");
    public static final TilePropertyKey NATURE_FLOOR = registerBase("natureFloor");
    public static final TilePropertyKey NEVER_CUTAWAY = registerBase("NeverCutaway");
    public static final TilePropertyKey NO_FREEZER = registerBase("NoFreezer");
    public static final TilePropertyKey NO_START = registerBase("noStart");
    public static final TilePropertyKey NO_WALL_LIGHTING = registerBase("NoWallLighting");
    public static final TilePropertyKey N_OFFSET = registerBase("Noffset");
    public static final TilePropertyKey OPAQUE_PIXELS_ONLY = registerBase("OpaquePixelsOnly");
    public static final TilePropertyKey OPEN = registerBase("open");
    public static final TilePropertyKey OPEN_TILE_OFFSET = registerBase("OpenTileOffset");
    public static final TilePropertyKey PAINTING_TYPE = registerBase("PaintingType");
    public static final TilePropertyKey PHYSICS_MESH = registerBase("PhysicsMesh");
    public static final TilePropertyKey PHYSICS_SHAPE = registerBase("PhysicsShape");
    public static final TilePropertyKey PICK_UP_LEVEL = registerBase("PickUpLevel");
    public static final TilePropertyKey PICK_UP_TOOL = registerBase("PickUpTool");
    public static final TilePropertyKey PICK_UP_WEIGHT = registerBase("PickUpWeight");
    public static final TilePropertyKey PLACE_TOOL = registerBase("PlaceTool");
    public static final TilePropertyKey PROPANE_TANK = registerBase("propaneTank");
    public static final TilePropertyKey RADIO = registerBase("radio");
    public static final TilePropertyKey RENDER_LAYER = registerBase("RenderLayer");
    public static final TilePropertyKey ROOF_GROUP = registerBase("RoofGroup");
    public static final TilePropertyKey SCRAP_SIZE = registerBase("ScrapSize");
    public static final TilePropertyKey SCRAP_TOOL_USE_OVERRIDE = registerBase("ScrapToolUseOverride");
    public static final TilePropertyKey SCRAP_USE_SKILL = registerBase("ScrapUseSkill");
    public static final TilePropertyKey SCRAP_USE_TOOL = registerBase("ScrapUseTool");
    public static final TilePropertyKey SEAT_MATERIAL = registerBase("SeatMaterial");
    public static final TilePropertyKey SIGNAL = registerBase("signal");
    public static final TilePropertyKey SINK_TYPE = registerBase("SinkType");
    public static final TilePropertyKey SLOPED_SURFACE_DIRECTION = registerBase("SlopedSurfaceDirection");
    public static final TilePropertyKey SLOPED_SURFACE_HEIGHT_MAX = registerBase("SlopedSurfaceHeightMax");
    public static final TilePropertyKey SLOPED_SURFACE_HEIGHT_MIN = registerBase("SlopedSurfaceHeightMin");
    public static final TilePropertyKey SMASHED_TILE_OFFSET = registerBase("SmashedTileOffset");
    public static final TilePropertyKey SMOKE = registerBase("smoke");
    public static final TilePropertyKey SNOW_TILE = registerBase("SnowTile");
    public static final TilePropertyKey SOLID = registerBase("solid");
    public static final TilePropertyKey SOLID_FLOOR = registerBase("solidfloor");
    public static final TilePropertyKey SOLID_TRANS = registerBase("solidtrans");
    public static final TilePropertyKey SPEAR_ONLY_ATTACK_THROUGH = registerBase("SpearOnlyAttackThrough");
    public static final TilePropertyKey SPRITE_GRID_LEVEL = registerBase("SpriteGridLevel");
    public static final TilePropertyKey SPRITE_GRID_POS = registerBase("SpriteGridPos");
    public static final TilePropertyKey STACK_REPLACE_TILE_OFFSET = registerBase("StackReplaceTileOffset");
    public static final TilePropertyKey STAIRS_BN = registerBase("stairsBN");
    public static final TilePropertyKey STAIRS_BW = registerBase("stairsBW");
    public static final TilePropertyKey STAIRS_MN = registerBase("stairsMN");
    public static final TilePropertyKey STAIRS_MW = registerBase("stairsMW");
    public static final TilePropertyKey STAIRS_TN = registerBase("stairsTN");
    public static final TilePropertyKey STAIRS_TW = registerBase("stairsTW");
    public static final TilePropertyKey STOP_CAR = registerBase("StopCar");
    public static final TilePropertyKey STREETLIGHT = registerBase("streetlight");
    public static final TilePropertyKey SURFACE = registerBase("Surface");
    public static final TilePropertyKey S_OFFSET = registerBase("Soffset");
    public static final TilePropertyKey TABLE_N = registerBase("tableN");
    public static final TilePropertyKey TAINTED_WATER = registerBase("taintedWater");
    public static final TilePropertyKey TALL_HOPPABLE_N = registerBase("TallHoppableN");
    public static final TilePropertyKey TALL_HOPPABLE_W = registerBase("TallHoppableW");
    public static final TilePropertyKey THUMP_SOUND = registerBase("ThumpSound");
    public static final TilePropertyKey TIE_SHEET_ROPE = registerBase("TieSheetRope");
    public static final TilePropertyKey TILE_OVERLAY = registerBase("TileOverlay");
    public static final TilePropertyKey TRANS = registerBase("trans");
    public static final TilePropertyKey TRANSLUCENT = registerBase("Translucent");
    public static final TilePropertyKey TRANSPARENT_FLOOR = registerBase("transparentFloor");
    public static final TilePropertyKey TRANSPARENT_N = registerBase("transparentN");
    public static final TilePropertyKey TRANSPARENT_W = registerBase("transparentW");
    public static final TilePropertyKey TREAT_AS_WALL_ORDER = registerBase("TreatAsWallOrder");
    public static final TilePropertyKey TREE = registerBase("tree");
    public static final TilePropertyKey TV = registerBase("TV");
    public static final TilePropertyKey UNBREAKABLE_WINDOW_N = registerBase("UnbreakableWindowN");
    public static final TilePropertyKey UNBREAKABLE_WINDOW_NW = registerBase("UnbreakableWindowNW");
    public static final TilePropertyKey UNBREAKABLE_WINDOW_W = registerBase("UnbreakableWindowW");
    public static final TilePropertyKey UNFLAMMABLE = registerBase("unflammable");
    public static final TilePropertyKey UNLIT = registerBase("unlit");
    public static final TilePropertyKey UNUSROOF_WALL_STARTD = registerBase("RoofWallStart");
    public static final TilePropertyKey USE_OBJECT_DEPTH_TEXTURE = registerBase("UseObjectDepthTexture");
    public static final TilePropertyKey VEGITATION = registerBase("vegitation");
    public static final TilePropertyKey WALL = registerBase("wall");
    public static final TilePropertyKey WALL_N = registerBase("WallN");
    public static final TilePropertyKey WALL_NW = registerBase("WallNW");
    public static final TilePropertyKey WALL_NW_TRANS = registerBase("WallNWTrans");
    public static final TilePropertyKey WALL_N_TRANS = registerBase("WallNTrans");
    public static final TilePropertyKey WALL_OBJECT_ALLOW_DOORFRAME = registerBase("WallObjectAllowDoorframe");
    public static final TilePropertyKey WALL_OVERLAY = registerBase("WallOverlay");
    public static final TilePropertyKey WALL_SE = registerBase("WallSE");
    public static final TilePropertyKey WALL_TYPE = registerBase("WallType");
    public static final TilePropertyKey WALL_W = registerBase("WallW");
    public static final TilePropertyKey WALL_W_TRANS = registerBase("WallWTrans");
    public static final TilePropertyKey WATER = registerBase("water");
    public static final TilePropertyKey WATER_AMOUNT = registerBase("waterAmount");
    public static final TilePropertyKey WATER_MAX_AMOUNT = registerBase("waterMaxAmount");
    public static final TilePropertyKey WATER_PIPED = registerBase("waterPiped");
    public static final TilePropertyKey WEST_ROOF_B = registerBase("WestRoofB");
    public static final TilePropertyKey WEST_ROOF_M = registerBase("WestRoofM");
    public static final TilePropertyKey WEST_ROOF_T = registerBase("WestRoofT");
    public static final TilePropertyKey WHEELIE_BIN = registerBase("WheelieBin");
    public static final TilePropertyKey WINDOW_FN = registerBase("windowFN");
    public static final TilePropertyKey WINDOW_FW = registerBase("windowFW");
    public static final TilePropertyKey WINDOW_LOCKED = registerBase("WindowLocked");
    public static final TilePropertyKey WINDOW_N = registerBase("WindowN");
    public static final TilePropertyKey WINDOW_W = registerBase("WindowW");
    public static final TilePropertyKey WIND_TYPE = registerBase("WindType");
    public static final TilePropertyKey W_OFFSET = registerBase("Woffset");

    private TilePropertyKey() {
    }

    public static TilePropertyKey register(String id) {
        return register(false, id);
    }

    private static TilePropertyKey registerBase(String id) {
        return register(true, id);
    }

    private static TilePropertyKey register(boolean allowDefaultNamespace, String id) {
        return Registries.TILE_PROPERTY_KEY.register(RegistryReset.createLocation(id, allowDefaultNamespace), new TilePropertyKey());
    }

    public static TilePropertyKey get(ResourceLocation id) {
        return Registries.TILE_PROPERTY_KEY.get(id);
    }

    @Override
    public String toString() {
        return Registries.TILE_PROPERTY_KEY.getLocation(this).toString();
    }
}
